### ISSUE TITLE
Fail to create new compendium

### ISSUE THREAD

**Issue by ratanakkim** [cstadther/adventure-import-export#144]
When trying to import new compendium to a game the module give this error :
![chrome_NlQc4rbwjz](https://user-images.githubusercontent.com/7220408/127834620-e9964a6b-83a7-4d7e-89b2-dfdc7667948e.png)

When trying to import a sizeable compendium this error was given: 
![chrome_0E13N85QQH](https://user-images.githubusercontent.com/7220408/127834720-2c8431d9-f255-4651-92eb-5acf6629ff19.png)

**Comment by zink-chimaera** [comment]
I can confirm this. I've created a scene compendium and exported it (without any error). After importing I get the same error:

```
common.js:439 undefined |  Error importing file Death House.fvttadv TypeError: Compendium.create is not a function
    at Function.getCompendiumPack (common.js:170)
    at adventure-import.js:499
    at async Function.asyncForEach (common.js:154)
    at async AdventureModuleImport._importCompendium (adventure-import.js:495)
    at async AdventureModuleImport._dialogButton (adventure-import.js:158) Error
    at Object.error (https://vtt.tuxdance.com/modules/adventure-import-export/src/common.js:439:53)
    at AdventureModuleImport._dialogButton (https://vtt.tuxdance.com/modules/adventure-import-export/src/adventure-import.js:463:24)
```

Have you found anything that can be done from a user's perspective work around this issue @ratanakkim ?

**Comment by zink-chimaera** [comment]
For futher information:
I was testing on D&D 5e with Foundry 0.8.9

**Comment by patrickporto** [comment]
`Compendium.create` is deprecated. An alternative is `CompendiumCollection.createCompendium`
